//权限管理
//角色
export const ACTION_ROLE_LIST = 'ACTION_ROLE_LIST'
//菜单资源
export const ACTION_MENU_LIST = 'ACTION_MENU_LIST'
// 按钮资源
export const ACTION_BTN_LIST = 'ACTION_BTN_LIST'
// 数据资源
export const ACTION_DATA_LIST = 'ACTION_DATA_LIST'
// 区块链列表
export const ACTION_BLOCKCHAIN_LIST = 'ACTION_BLOCKCHAIN_LIST'
// 区块链下拉列表
export const ACTION_BLOCKCHAIN_OPTION = 'ACTION_BLOCKCHAIN_OPTION'
