export const button_list={
	// 账户审核
	"auditpass_accountKey":"auditpass_account",
	"auditpass_accountName":"审核通过",
	"auditnopass_accountKey":"auditnopass_account",
	"auditnopass_accountName":"审核不通过",
	// 账户维护
	"query_accountKey":"query_account",
	"query_accountName":"查询",
	"edit_accountKey":"edit_account",
	"edit_accountName":"编辑",
	"detail_accountKey":"detail_account",
	"detail_accountName":"查看详细",
	"cancel_accountKey":"cancel_account",
	"cancel_accountName":"注销",
	"inport_accountKey":"inport_account",
	"inport_accountName":"导入账户信息",
	"export_accountKey":"export_account",
	"export_accountName":"导出账户信息",
	// 账户状态跟踪
	"query_accounttraceKey":"query_accounttrace",
	"query_accounttraceName":"查询",
	"detail_accountinfoKey":"detail_accountinfo",
	"detail_accountinfoName":"查看详细",
	"query_accountassetKey":"query_accountasset",
	// 资产创建
	"query_accountassetName":"查询",
	"detail_accountassetKey":"detail_accountasset",
	"detail_accountassetName":"查看详细",
	"create_accountassetKey":"create_accountasset",
	"create_accountassetName":"资产创建",
	// 资产记录查询
	"query_assettraceKey":"query_assettrace",
	"query_assettraceName":"查询",
	// 角色管理
	"add_roleKey":"add_role",
	"add_roleName":"添加角色",
	"query_roleKey":"query_role",
	"query_roleName":"查询",
	"edit_roleKey":"edit_role",
	"edit_roleName":"编辑",
	"maintain_rolerightKey":"maintain_roleright",
	"maintain_rolerightName":"权限维护",
	"delete_roleKey":"delete_role",
	"delete_roleName":"删除",
	"save_rolerightKey":"save_roleright",
	"save_rolerightName":"保存",
	// 菜单资源
	"add_menuresourceKey":"add_menuresource",
	"add_menuresourceName":"创建菜单资源",
	"query_menuresourceKey":"query_menuresource",
	"query_menuresourceName":"查询",
	"edit_menuresourceKey":"edit_menuresource",
	"edit_menuresourceName":"编辑",
	"delete_menuresourceKey":"delete_menuresource",
	"delete_menuresourceName":"删除",
	"add_buttonresourceKey":"add_buttonresource",
	"add_buttonresourceName":"创建按钮资源",
	"query_buttonresourceKey":"query_buttonresource",
	"query_buttonresourceName":"查询",
	"edit_buttonresourceKey":"edit_buttonresource",
	"edit_buttonresourceName":"编辑",
	"delete_buttonresourceKey":"delete_buttonresource",
	"delete_buttonresourceName":"删除",
	"add_dataresourceKey":"add_dataresource",
	"add_dataresourceName":"创建数据资源",
	"query_dataresourceKey":"query_dataresource",
	"query_dataresourceName":"查询",
	"eidt_dataresourceKey":"eidt_dataresource",
	"eidt_dataresourceName":"编辑",
	"delete_dataresourceKey":"delete_dataresource",
	"delete_dataresourceName":"删除",
	// 文件管理
	"create_contractKey":"create_contract",
	"create_contractName":"创建合约",
	"import_contractKey":"import_contract",
	"import_contractName":"导入合约",
	"query_contractproductinfileKey":"query_contractproductinfile",
	"query_contractproductinfileName":"查询",
	"edit_contractproductKey":"edit_contractproduct",
	"edit_contractproductName":"编辑",
	"send_contractproductKey":"send_contractproduct",
	"send_contractproductName":"送审",
	"update_contractproductKey":"update_contractproduct",
	"update_contractproductName":"查看修改意见",
	"delete_contractproductKey":"delete_contractproduct",
	"delete_contractproductName":"删除",
	// 合约产品
	"query_contractproductinproductKey":"query_contractproductinproduct",
	"query_contractproductinproductName":"查询",
	"pass_contractproductKey":"pass_contractproduct",
	"pass_contractproductName":"同意",
	"nopass_contractproductKey":"nopass_contractproduct",
	"nopass_contractproductName":"建议修改",
	"release_contractproductKey":"release_contractproduct",
	"release_contractproductName":"发布",
	"sign_contractKey":"sign_contract",
	"sign_contractName":"签约",
	// 执行合约
	"query_contractKey":"query_contract",
	"query_contractName":"查询",
	// 转账合约
	"transfer_moneyKey":"transfer_money",
	"transfer_moneyName":"确定"
}
